[font]
normal = { family = "CommitMono", style = "Regular" }
size = 11

[window]
decorations = "None"
padding = { x = 5, y = 5 }

[colors.primary]
background = "#1e1e1e"
foreground = "#d0d0d0"

[colors.normal]
black = "#1e1e1e"
red = "#a87878"
green = "#669985"
yellow = "#a87878"
blue = "#669985"
magenta = "#669985"
cyan = "#669985"
white = "#d0d0d0"

[colors.bright]
black = "#252525"
red = "#a87878"
green = "#669985"
yellow = "#a87878"
blue = "#669985"
magenta = "#669985"
cyan = "#669985"
white = "#d0d0d0"

[colors.cursor]
text = "#1e1e1e"
cursor = "#669985"
