[font]
normal = { family = "CommitMono", style = "Regular" }
size = 11

[window]
decorations = "None"

[colors.primary]
background = "#1E1E1E"
foreground = "#DADADA"

[colors.normal]
black = "#1E1E1E"
red = "#E46876"
green = "#9ECE6A"
yellow = "#E0AF68"
blue = "#5C9A8E"
magenta = "#BB9AF7"
cyan = "#7DCFFF"
white = "#DADADA"

[colors.bright]
black = "#262626"
red = "#E46876"
green = "#9ECE6A"
yellow = "#E0AF68"
blue = "#5C9A8E"
magenta = "#BB9AF7"
cyan = "#7DCFFF"
white = "#B0B0B0"
